openapi: 3.0.3
info:
  title: Product service api
  description: |
   - [Product api allows the user to manipulate product data, searching by id, returning all registered products, modifying, deleting or creating new products.]
  version: 1.0
servers:
  - url: "http://localhost:8080"
    description: Generated server url
paths:
  /products:
    get:
      summary: Returns a list products
      operationId: getAllProducts
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDTO'
        '404':
          description: Product not found
    post:

      summary: Add a new product to the database
      operationId: creatProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDTO'

        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                $ref: '#/components/schemas/ProductDTO'
        '405':
          description: Invalid input

  /products/{Id}:
    get:
      summary: Find product by ID
      description: Returns a single product
      operationId: getProductById
      parameters:
        - name: productId
          in: path
          description: ID of product to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDTO'

        '400':
          description: Invalid ID supplied
        '404':
          description: Product not found


    put:

      summary: Updates a product
      description: ''
      operationId: updateProduct
      parameters:
        - name: productId
          in: path
          description: ID of product that needs to be updated
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '405':
          description: Invalid input


    delete:

      summary: Deletes a product
      description: delete a product
      operationId: deleteProduct
      parameters:
        - name: api_key
          in: header
          description: ''
          required: false
          schema:
            type: string
        - name: productId
          in: path
          description: Product id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid product value
components:
  schemas:
    ProductDTO:
    required:
      - name,
      - value,
      - description
    type: object
    properties:
      name:
        type: string
      value:
        type: number
      description:
        type: string
