spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_ecommerce?createDatabaseIfNotExist=true&severTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true
  sql:
    init:
      mode: always
springdoc:
  openapi:
    enabled: true
  swagger-ui:
    enabled: true
